project:
  type: website

website:
  title: "ESGI 187"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: industry.qmd
        text: Organisations
      - href: participants.qmd
        text: Participants
      - conduct.qmd
      - venue.qmd
      - contact.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



