project:
  type: website

website:
  title: "ESGI 187"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: participants.qmd
        text: For participants
      - schedule.qmd
      - href: problems.qmd
        text: Problems
      - conduct.qmd
      - venue.qmd
      - contact.qmd

format:
  html:
    theme: [united, theme.scss]
    css: styles.css
    toc: true

execute: 
  freeze: auto