---
title: "ESGI 187"
---

The 187th ESGI will be held on **14-18 July 2025** at the **University of Bristol**. 

# About the ESGI

The European Study Group with Industry (ESGI) is a five-day intense workshop that brings together mathematical scientists and partners from business, industry, and government.  Partners present a pressing problem they are currently facing, and mathematical scientists work on finding a solution. ESGIs are internationally recognised as a cost-effective means of making real progress on current challenges in just a few days.


# ESGI Format
 
ESGI 187 will follow the tried-and-tested format:

* On the first day of the workshop, each organisation presents their challenges.

* The mathematical scientists then split into groups, and for the next three days work closely with each external partner representative to brainstorm ideas, model scenarios, and problem solve.

* On the final day, each group presents their progress and recommended routes forward. 

* After the meeting, appropriate deliverables from the week will be made available to the organisation; traditionally this has been a technical report summarising the week’s work.  Examples of past reports can be found in the [MIIR repository](https://www.cambridge.org/engage/miir/public-dashboard).

 * In principle, there are no limits to the problems that can be tackled by mathematical modelling! We are expecting over 70 mathematical scientists from across the UK and Europe to participate in our workshop with expertise in, for example, statistical modelling, fluid and solid mechanics, heat and mass transport, data science, and machine learning.

