---
title: "Information for potential problem presenters"
---

If you think that your organisation would benefit from presenting a problem at ESGI 187, then please [submit an expression of interest form](https://forms.office.com/e/Q8Jm1Sr4Mr).  The event organisers will arrange a time for an online meeting with you shortly after to discuss problem ideas or provide more information about the event.

Almost all real-world problems have some mathematical or data modelling aspect to them, although this may not be recognisable at first. Indeed, from our own experience, some of the most successful study group problems were not well-defined in technical terminology at the start of the study group. Study group problems can come from a wide range of areas, such as engineering, electronics, transport, agriculture, energy, finance, and medicine. For more information on past study groups, including a description of some of the problems which have been presented at previous meetings, see the [project descriptions](https://sites.google.com/view/180esgi/problem-descriptions) from last year's UK ESGI.

Company representatives may be present only on the first day (to expose their problems) and on the last day (for the results), but they may also stay the entire week to brainstorm ideas and provide feedback.

After the event, a report on each problem will be sent to the company.  Funding may be available for the group to visit your organisation after the event to discuss follow-up work.

There is a fee for presenting a problem at ESGI 187.  For more information about fees or for general inquires about presenting a problem or the event, please [contact the organisers](contact.qmd).