---
title: "Information for participants"
---

Please read below for information about registration, 
accommodation, lunches, and evening events.


## Room allocation for projects

TBA

## Report inappropriate behaviour

Use the form below to anonymously report inappropriate behaviour
at ESGI 187.  The form will only be read by study group organisers.

* [Report an inappropriate behaviour](https://forms.office.com/e/EXxQkMDjdL)

## Colemanballs

Use the form below to submit a Colemanball that you overheard!

* [Submit a Colemanballs](https://forms.office.com/e/7P7gDrNnw3)

## Accommodation

A welcome pack with accommodation details has been emailed to everyone who has been allocated a room in university accommodation.  If you have not received this but are expected to stay in a room, please [contact the organisers](/contact.qmd).


## Lunches

Lunch will be provided free of charge.  Lunch will take place in the common room of the [Ada Lovelace Building](venue.qmd).

## Evening events

There is a group dinner on Monday night at [Lost and Found](https://www.lostandfoundbristol.co.uk/) starting at 1900.

On Thursday, the Ada Lovelace Building will be open until 10 pm.  Pizza and drinks will be served starting from 1800.