---
title: Registration
---

Registration for ESGI 187 is now open!  

## Early-bird registration

Early-bird registration closed on 1 May.  Decisions about university-provided accommodation have been communicated.

Those who submitted an early-bird registration form were
asked to confirm their attendance by 13 June.  If you 
did not confirm your attendance, then you will not be
registered for the event and any accommodation you requested
will have been allocated to someone else.

## Standard registration

<<<<<<< HEAD
Registration for the event is now closed.  Joining instructions have been emailed to everyone who has successfully registered.

=======
Please use the form below to register for ESGI 187:

* [ESGI 187 registration form](https://forms.office.com/e/zVerNw68zq)

There are a small number of accommodation spaces still available.  To request a space, please say that you will join the waiting list for accommodation when submitting the registration form. The organisers will contact you to confirm your accommodation and registration.
>>>>>>> refs/remotes/origin/main

## Visa invitation letters

It is no longer possible to request a visa invitation letter for
the event.