---
title: "Venue"
---

## The Ada Lovelace Building

ESGI 187 will be hosted by the School of Engineering Mathematics and Technology at the Univeristy of Bristol.
The school is housed in the Ada Lovelace Building, which
is part of Bristol's historic Clifton campus.

School of Engineering Mathematics and Technology  
Ada Lovelace Building  
University of Bristol  
Tankard's Close  
Bristol  
BS8 1TW


<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2486.016978051309!2d-2.603347423057251!3d51.45784471432205!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48718d90377d70df%3A0x1c07965b16bf91c3!2sDepartment%20of%20Engineering%20Mathematics%20and%20Technology%20-%20University%20of%20Bristol!5e0!3m2!1sen!2suk!4v1734610823425!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>


## The Ivy Gate Building

Some projects will be based in the Ivy Gate Building.  The easiest way
to get to the Ivy Gate Building from the Ada Lovelace Building is to walk through the garden of the Ada Lovelace Building, which can be accessed through its common room.

It's also possible to walk there from the main entrance of the Ada Lovelace Building as shown in the map below:

<iframe src="https://www.google.com/maps/embed?pb=!1m28!1m12!1m3!1d553.4051249256131!2d-2.6013528056000204!3d51.45833829514651!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m13!3e2!4m5!1s0x48718d90377d70df%3A0x1c07965b16bf91c3!2sDepartment%20of%20Engineering%20Mathematics%20and%20Technology%20-%20University%20of%20Bristol%2C%20Tankard&#39;s%20Close%2C%20Bristol!3m2!1d51.457845899999995!2d-2.6007061!4m5!1s0x48718dd1ae44632f%3A0xcf3fd032edc10db!2sIvy%20Gate%20Building%2C%20Tyndall%20Ave%2C%20Bristol%20BS8%201FD!3m2!1d51.4586373!2d-2.6013105!5e0!3m2!1sen!2suk!4v1752158084955!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>